# Generated by Django 2.0.1 on 2018-02-28 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challengica_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='setno',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='challengica_app.SetNo'),
        ),
    ]
