# Generated by Django 2.0.1 on 2018-03-14 05:10

import challengica_app.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challengica_app', '0002_contestant_setno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='endtime',
            field=models.DateTimeField(default=challengica_app.models.setendtime, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start time'),
        ),
    ]
