# Generated by Django 2.0.1 on 2018-03-14 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challengica_app', '0004_contestant_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
